### ISSUE TITLE
Inline code rendering is barely readable with the Advanced Markdown extension

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#136]
See below. Ideally, inline code would be visually very different from regular text. E.g. with the same background as when formatting a regular code block. Here's how Github format things: `$sudo apt-get install git`. Very readable and close to what I have in mind for Standard Notes Web.

![markdown-inline-code-rendering](https://user-images.githubusercontent.com/293478/27906060-46079918-6242-11e7-91c9-14603b9b2efd.gif)

**Comment by mobitar** [comment]
To be honest with you, bugs with individual editors stand a far better chance of being fixed with the original project repo. In this case, this is the SimpleMDE editor found here: https://github.com/sparksuite/simplemde-markdown-editor

**Comment by anavarre** [comment]
Understood. Filed https://github.com/sparksuite/simplemde-markdown-editor/issues/604 accordingly.

I'm using https://github.com/timsayshey/Ghost-Markdown-Editor (I think) with Ghost CMS and it renders things really well FYI.

**Comment by mobitar** [comment]
That looks similar to the Simple Markdown Editor for SN. Have you tried that one?

**Comment by anavarre** [comment]
I have but unfortunately it's not usable for me as long as https://github.com/standardnotes/web/issues/114 isn't fixed, because the panels would be very, very narrow (especially because I also zoom in the page for better readability)
